### ISSUE TITLE
absent sorting functional

### ISSUE THREAD

**Issue by AydarBelhomme** [lukasz-kusek/xml-comparator#1]
Hi, I wanna tell you thank you for this code and I have a question about possibility to use some sort methods after methods compare. For example If we compared two xml file then some notes and differences given not sorted. How we can solve this problem? Thank you.

**Comment by lukasz-kusek** [comment]
Hi @AydarBelhomme , could you give me some XML examples and expected results?

**Comment by AydarBelhomme** [comment]
Оk. For example I compare this xml 

```
<CigResult xmlns="" xmlns:ns2="http://ws.creditinfo.com/" Version="4.0">
  <DateTime>01.03.2017 11:56:45</DateTime>
  <ReferenceId>10</ReferenceId>
  <ServiceName>Front Office WS</ServiceName>
  <ResultCulture>ru-RU</ResultCulture>
  <ResultCode>10</ResultCode>
  <ResultDescription />
  <UsageIdentity />
</CigResult>
```
[example1.txt](https://github.com/lukasz-kusek/xml-comparator/files/1281046/example1.txt)

With this for example 

```
<CigResult Version="3.0.1">
                  <DateTime>04.09.2017 11:57:30</DateTime>
                  <ReferenceId/>
                  <ServiceName>Front Office WS</ServiceName>
                  <ResultCulture>ru-RU</ResultCulture>
                  <ResultCode/>
                  <ResultDescription/>
                  <UsageIdentity/>
</CigResult>
```
[example2.txt](https://github.com/lukasz-kusek/xml-comparator/files/1281047/example2.txt)

And Result like that: 

```
>>> Comparing 001140002597.xml to 001140002597.xml
/CigResult/ReferenceId/text() :: DO: 10. POSLE: [null]
/CigResult/DateTime/text() :: DO: 01.03.2017 11:56:45. POSLE: 04.09.2017 11:57:30
/CigResult/ResultCode/text() :: DO: 10. POSLE: [null]
/CigResult/@Version :: DO: 4.0. POSLE: 3.0.1
```

If you notice, result written in descend form. 
Thank you.

**Comment by lukasz-kusek** [comment]
Thank you. I'll have a look.

**Comment by lukasz-kusek** [comment]
@AydarBelhomme, do you want to sort the result only?
Will this work for you:

```
List<String> messages =
                diff.getDifferenceInformationSet()
                        .stream()
                        .sorted(Comparator.comparing(DifferenceInformation::getXPath))
                        .map(DifferenceInformation::getMessage)
                        .collect(Collectors.toList());
```
?

**Comment by AydarBelhomme** [comment]
I write result not for Set(String), and for Set(DifferenceInformation).

**Comment by lukasz-kusek** [comment]
@AydarBelhomme, do you mean this:

```
List<DifferenceInformation> result =
                diff.getDifferenceInformationSet()
                        .stream()
                        .sorted(Comparator.comparing(DifferenceInformation::getXPath))
                        .collect(Collectors.toList());
```

**Comment by AydarBelhomme** [comment]
Thanks, I solved this by Map. 
 Map<String, String> sortedDiff = new TreeMap<>();
sortedDiff.put(diffInfo.getXPath(), message);
for(Map.Entry e : sortedDiff.entrySet()){
                                log.info(e.getKey() + " :: " + e.getValue());
                            }

**Comment by lukasz-kusek** [comment]
Cool. Closing the issue.

**Comment by AydarBelhomme** [comment]
Sorry, but I need sorted elements from messages by XPath, my solution is incorrect.
